<a href="https://colab.research.google.com/github/Aashima593/Training-TR-103-Report/blob/main/Day28.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cross Validation

<h2>K- Fold Cross Validation</h2>
<img src="https://datamites.com/blog/uploads/images/2023/11/image_750x_6543bfa5e5864.jpg" width=800px>
<img src="https://global.discourse-cdn.com/dlai/original/3X/a/3/a3ed2de61c2b4fa00f1b7e939753e1a7e181afb0.png" width=800px>




# Bagging

Bagging (short for Bootstrap Aggregating) is an ensemble learning technique that aims to improve the accuracy and stability of machine learning models by training multiple models on different random subsets of the training data and then combining their predictions.

<img src="https://miro.medium.com/v2/resize:fit:1050/1*a6hnuJ8WM37mLimHfMORmQ.png" width=700px>




# Boosting

Boosting is an ensemble learning technique in machine learning that combines multiple weak learners (models that perform slightly better than random guessing) sequentially, where each new model focuses on correcting the errors made by the previous ones. The final prediction is made by aggregating the predictions of all models (e.g., via weighted voting or averaging).



<img src="https://miro.medium.com/v2/resize:fit:1050/1*4XuD6oRrgVqtaSwH-cu6SA.png" width=700px>

# Encoding

Encoding is the process of converting categorical data (non-numeric) into a numerical format so that machine learning algorithms can understand and process it. Most ML models can only work with numbers, so encoding is essential when dealing with text-based or categorical features.

## Ordinal Encoding

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("customer_dataset.csv")
df.head()

age  gender     review education purchased
0   66    Male    Average    School       Yes
1   29    Male    Average    School        No
2   75  Female    Average       PhD        No
3   35  Female  Excellent    School        No
4   38    Male       Poor    School        No

In [3]:
df.head()

age  gender     review education purchased
0   66    Male    Average    School       Yes
1   29    Male    Average    School        No
2   75  Female    Average       PhD        No
3   35  Female  Excellent    School        No
4   38    Male       Poor    School        No

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:3], df.iloc[:, -1], test_size=0.2)

In [5]:
x_train

gender     review
320  Female  Excellent
352  Female       Good
253    Male    Average
321  Female  Excellent
407  Female       Good
..      ...        ...
296    Male       Good
32   Female  Excellent
462    Male       Good
54     Male       Poor
460  Female       Poor

[400 rows x 2 columns]

In [6]:
y_train

320     No
352    Yes
253     No
321     No
407     No
      ... 
296     No
32      No
462    Yes
54      No
460     No
Name: purchased, Length: 400, dtype: object

In [7]:
from sklearn.preprocessing import OrdinalEncoder

# Create an object of ordinal encode
# pass the parameters categories in the form of list in which you want to apply the ordinal encoding and pass the values in ascending order
oe = OrdinalEncoder(categories=[['Male', 'Female'], ['Poor', 'Average', 'Good','Excellent']])

In [8]:
oe.fit(x_train)

x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

In [9]:
x_train

array([[1., 3.],
       [1., 2.],
       [0., 1.],
       [1., 3.],
       [1., 2.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 3.],
       [1., 3.],
       [0., 2.],
       [1., 2.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 3.],
       [0., 1.],
       [0., 3.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 1.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [1., 2.],
       [0., 1.],
       [1., 3.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [1., 3.],
       [1., 2.],
       [1., 2.],
       [1., 0.],
       [0., 3.],
       [1., 3.],
       [1., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [1., 3.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 2.],
       [1., 1.

In [10]:
oe.categories

[['Male', 'Female'], ['Poor', 'Average', 'Good', 'Excellent']]

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [12]:
le.fit(y_train)

y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [13]:
le.classes_

# 0 - No
# 1 - Yes

array(['No', 'Yes'], dtype=object)

In [14]:
y_test

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1])

## Nominal Encoding

<img src="https://miro.medium.com/v2/resize:fit:1400/1*ggtP4a5YaRx6l09KQaYOnw.png" width=900px>

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [16]:
df = pd.read_csv('customer_dataset.csv')
df.head()

age  gender     review education purchased
0   66    Male    Average    School       Yes
1   29    Male    Average    School        No
2   75  Female    Average       PhD        No
3   35  Female  Excellent    School        No
4   38    Male       Poor    School        No

In [17]:
df.gender.value_counts()
df.gender.unique()

array(['Male', 'Female'], dtype=object)

In [18]:
df.review.value_counts()

review
Good         132
Average      130
Poor         127
Excellent    111
Name: count, dtype: int64

In [19]:
# On owner and fuel type

pd.get_dummies(df, columns=['gender', 'review'])


age education purchased  gender_Female  gender_Male  review_Average  \
0     66    School       Yes          False         True            True   
1     29    School        No          False         True            True   
2     75       PhD        No           True        False            True   
3     35    School        No           True        False           False   
4     38    School        No          False         True           False   
..   ...       ...       ...            ...          ...             ...   
495   61       PhD       Yes          False         True            True   
496   63        UG       Yes          False         True           False   
497   28        PG       Yes          False         True            True   
498   29        UG       Yes          False         True            True   
499   45    School        No          False         True           False   

     review_Excellent  review_Good  review_Poor  
0               False        False        False  
1               False        False        False  
2               False        False        False  
3                True        False        False  
4               False        False         True  
..                ...          ...          ...  
495             False        False        False  
496             False        False         True  
497             False        False        False  
498             False        False        False  
499             False        False         True  

[500 rows x 9 columns]

In [20]:
# K-1 One Hot Encoding

pd.get_dummies(df, columns=['gender', 'review'], drop_first=True)

age education purchased  gender_Male  review_Excellent  review_Good  \
0     66    School       Yes         True             False        False   
1     29    School        No         True             False        False   
2     75       PhD        No        False             False        False   
3     35    School        No        False              True        False   
4     38    School        No         True             False        False   
..   ...       ...       ...          ...               ...          ...   
495   61       PhD       Yes         True             False        False   
496   63        UG       Yes         True             False        False   
497   28        PG       Yes         True             False        False   
498   29        UG       Yes         True             False        False   
499   45    School        No         True             False        False   

     review_Poor  
0          False  
1          False  
2          False  
3          False  
4           True  
..           ...  
495        False  
496         True  
497        False  
498        False  
499         True  

[500 rows x 7 columns]

**One Hot Encoding using Sklearn (Recommended)**

In [21]:
df.head()

age  gender     review education purchased
0   66    Male    Average    School       Yes
1   29    Male    Average    School        No
2   75  Female    Average       PhD        No
3   35  Female  Excellent    School        No
4   38    Male       Poor    School        No

In [22]:
# Splitting the dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 0:4], df.iloc[:, -1], test_size=0.2, random_state=2)

In [23]:
x_train.head()
y_train.head()

428     No
490    Yes
53      No
336    Yes
154     No
Name: purchased, dtype: object

In [24]:
from sklearn.preprocessing import OneHotEncoder

In [25]:
ohe = OneHotEncoder()


# To apply OHE, we need to separate out the columns from dataframe, apply the OHE and then add with existing dataframe

In [26]:
# Applying the OHE on the columns
ohe.fit_transform(x_train[['gender', 'review']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 800 stored elements and shape (400, 6)>

In [27]:
x_train_new = ohe.fit_transform(x_train[['gender', 'review']]).toarray()

In [28]:
x_test_new = ohe.transform(x_test[['gender', 'review']]).toarray()


In [29]:
x_train_new

array([[1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0.],
       ...,
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0.]])

In [30]:
# Converting the x_train dataframe into numpy array
x_train[['gender', 'review']].values

array([['Female', 'Good'],
       ['Male', 'Poor'],
       ['Female', 'Excellent'],
       ['Female', 'Poor'],
       ['Female', 'Poor'],
       ['Female', 'Good'],
       ['Male', 'Good'],
       ['Male', 'Excellent'],
       ['Male', 'Poor'],
       ['Male', 'Good'],
       ['Female', 'Excellent'],
       ['Male', 'Good'],
       ['Male', 'Good'],
       ['Female', 'Poor'],
       ['Female', 'Good'],
       ['Male', 'Poor'],
       ['Male', 'Average'],
       ['Female', 'Average'],
       ['Male', 'Good'],
       ['Male', 'Average'],
       ['Female', 'Excellent'],
       ['Female', 'Good'],
       ['Female', 'Average'],
       ['Female', 'Poor'],
       ['Female', 'Good'],
       ['Female', 'Average'],
       ['Female', 'Poor'],
       ['Male', 'Poor'],
       ['Female', 'Poor'],
       ['Female', 'Average'],
       ['Female', 'Excellent'],
       ['Female', 'Average'],
       ['Female', 'Excellent'],
       ['Male', 'Average'],
       ['Female', 'Average'],
       ['Female', 'Excel

In [31]:
# Appending the both np array horizontally
np.hstack((x_train[['gender', 'review']].values, x_train_new))

array([['Female', 'Good', 1.0, ..., 0.0, 1.0, 0.0],
       ['Male', 'Poor', 0.0, ..., 0.0, 0.0, 1.0],
       ['Female', 'Excellent', 1.0, ..., 1.0, 0.0, 0.0],
       ...,
       ['Female', 'Poor', 1.0, ..., 0.0, 0.0, 1.0],
       ['Female', 'Good', 1.0, ..., 0.0, 1.0, 0.0],
       ['Male', 'Good', 0.0, ..., 0.0, 1.0, 0.0]], dtype=object)

In [32]:
df.head()

age  gender     review education purchased
0   66    Male    Average    School       Yes
1   29    Male    Average    School        No
2   75  Female    Average       PhD        No
3   35  Female  Excellent    School        No
4   38    Male       Poor    School        No

In [33]:
counts = df['gender'].value_counts()

In [34]:
df['review'].nunique()
threshold = 100

In [35]:
# brands with value less than threshold will be replaced by others

repl = counts[counts <= threshold].index

In [36]:
repl

Index([], dtype='object', name='gender')

In [37]:
pd.get_dummies(df['review'].replace(repl, 'uncommon'))

Average  Excellent   Good   Poor
0       True      False  False  False
1       True      False  False  False
2       True      False  False  False
3      False       True  False  False
4      False      False  False   True
..       ...        ...    ...    ...
495     True      False  False  False
496    False      False  False   True
497     True      False  False  False
498     True      False  False  False
499    False      False  False   True

[500 rows x 4 columns]